name: Build zip

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: zip -r -x ".*" resourcepack.zip .
      - uses: actions/upload-artifact@v3
        with:
          path: resourcepack.zip
