name: Build zip

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          sudo apt-get install zip -y
          zip -r resourcepack.zip .
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add resourcepack.zip
          git commit -m "Auto generate resourcepack.zip"
          git push
